[package]
name = "first_robot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-rs = {path = "/home/richie/VEX/vex-rs"}