compile:
	cargo build --release
	bash build/finish_link.sh

clean:
	cargo clean

slot1:
	bash build/flash.sh 1

slot2:
	bash build/flash.sh 2 

slot3:
	bash build/flash.sh 3

slot4:
	bash build/flash.sh 4

slot5:
	bash build/flash.sh 5

slot6:
	bash build/flash.sh 6

slot7:
	bash build/flash.sh 7

slot8:
	bash build/flash.sh 8